GET http://localhost:8080/persons
Accept: application/json

###
POST http://localhost:8080/persons
Content-Type: application/json

{
  "first": "daniel",
  "last": "düsentrieb",
  "birth": "1970-10-10"
}

###


